### ISSUE TITLE
Questions about performance

### ISSUE THREAD

**Issue by gzwo-O** [littleredxh/HardNegative#3]
Thanks for your excellent work. But when I run the code on CAR196 datasets, I found that the recall@1 on CAR196 is 61.1%, which is far from the result in paper 73.3. Since the data_dict_emb.pth file is generated by myself, I don't know if my file generation method is wrong or other parameters need to be adjusted to achieve the performance in the paper. I am looking forward to your reply. 
Thanks!!!

**Comment by littleredxh** [comment]
Have you check the parity with my experiment log(exp_CAR/_result/CAR_R50/)?
